TestProject/Models/DummyModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestProject.Models
{
    public class DummyModel
    {
        public DummyModel() { }

        public DummyModel(int id, string name)
        {
            Id = id;
            Name = name;
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [StringLength(256)]
        public string Name { get; set; }
    }
}

TestProject/Controllers/DummyModelsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;
using TestProject.Data;
using TestProject.Models;
using TestProject.ViewModels;

namespace TestProject.Controllers
{
    public class DummyModelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<DummyModelsController> _logger;

        public DummyModelsController(ILogger<DummyModelsController> logger, ApplicationDbContext context)
        {
            _context = context;
            _logger = logger;
        }

        // GET: DummyModels
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Index route visited");

            var dummyModels = await _context.DummyModels.ToListAsync();

            var viewModel = new DummyModelsIndexViewModel { DummyModels = dummyModels };

            return View(viewModel);
        }

        // GET: DummyModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) {
                return NotFound();
            }

            var dummyModel = await _context.DummyModels.FirstOrDefaultAsync(m => m.Id == id);
            if (dummyModel == null) {
                return NotFound();
            }

            return View(dummyModel);
        }

        // GET: DummyModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DummyModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] DummyModel dummyModel)
        {
            if (ModelState.IsValid) {
                _context.Add(dummyModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dummyModel);
        }

        // GET: DummyModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) {
                return NotFound();
            }

            var dummyModel = await _context.DummyModels.FindAsync(id);
            if (dummyModel == null) {
                return NotFound();
            }
            return View(dummyModel);
        }

        // POST: DummyModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] DummyModel dummyModel)
        {
            if (id != dummyModel.Id) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(dummyModel);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!DummyModelExists(dummyModel.Id)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dummyModel);
        }

        // GET: DummyModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) {
                return NotFound();
            }

            var dummyModel = await _context.DummyModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dummyModel == null) {
                return NotFound();
            }

            return View(dummyModel);
        }

        // POST: DummyModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dummyModel = await _context.DummyModels.FindAsync(id);
            _context.DummyModels.Remove(dummyModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DummyModelExists(int id)
        {
            return _context.DummyModels.Any(e => e.Id == id);
        }
    }
}

TestProject/Views/DummyModels/Create.cshtml
@model DummyModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DummyModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="DummyModels" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestProject/Views/DummyModels/Delete.cshtml
@model DummyModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DummyModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TestProject/Views/DummyModels/Details.cshtml
@model DummyModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DummyModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TestProject/Views/DummyModels/Edit.cshtml
@model DummyModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DummyModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestProject/Views/DummyModels/Index.cshtml
@model DummyModelsIndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.DummyModels) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-controller="DummyModels" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-controller="DummyModels" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-controller="DummyModels" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>